#!/usr/bin/env bash
#
# Build a windows binary from linux
#

set -eu -o pipefail

source /cross/.variables

export CC=x86_64-w64-mingw32-gcc
export CGO_ENABLED=1
export GOOS=windows
export GOARCH=amd64

# Override TARGET
TARGET="${GOPATH}/bin/$NAME-$GOOS-$GOARCH"

# echo "Generating windows resources"
# go generate /cross/winresources

echo "Building $TARGET"
go build -buildmode="${BUILDMODE}" -o "${TARGET}" -ldflags "${LDFLAGS}" -gcflags "${GCFLAGS}" -asmflags "${ASMFLAGS}" "${SOURCE}"
